title: ntRNA 
description: ntRNA Databae  
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://drive.google.com/file/d/1nkL7byWyFKt-mfdO_YgTUZ912ZG9SFZL/view?usp=drive_link
  another_url: another value
css:
  - "/assets/css/custom.css"
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-feed
include:
  - _pages
