title: ntRN 
description: ntRNA Database
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://drive.google.com/file/d/1nkL7byWyFKt-mfdO_YgTUZ912ZG9SFZL/view?usp=drive_link
  another_url: another value
